os: linux
dist: focal
language: python

python:
  - 3.12

install:
  - sudo apt-get update
  - sudo apt-get install -y python3-dev python3-distutils python3-pip git pkg-config libssl-dev build-essential libffi-dev zlib1g-dev libncurses5-dev libgdbm-dev libc6-dev libsqlite3-dev libreadline-dev libbz2-dev zip unzip openjdk-8-jdk autoconf libtool cmake
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
  - python3 setup.py install
  - cd ..
  - pip3 install --upgrade cython buildozer python-for-android

script:
  - export PATH=$PATH:~/.local/bin/
  - buildozer android debug

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: bin/mobileapp001-0.3-armeabi-v7a-debug.apk
  skip_cleanup: true
  on:
    tags: true

after_success:
  - rm -rf .buildozer
  - cp -f buildozer-64bit.spec buildozer.spec
  - buildozer android release
  - dpl releases --token $g_token --file "bin/mobileapp001-0.3-arm64-v8a-release-unsigned.apk" --tag_name "v.0.3"
