os: linux
dist: focal
language: python

python:
  - 3.12

install:
  - sudo apt-get install python3-dev
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - sudo apt-get update
  - sudo apt-get install pkg-config libssl-dev
  - sudo apt-get install -y python3-pip build-essential git python3-dev libssl-dev libffi-dev zlib1g-dev libncurses5-dev libgdbm-dev libc6-dev libsqlite3-dev libreadline-dev libbz2-dev
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - ls -l
  - cd buildozer
  - ls -l
  - python3 setup.py install
  - ls -l
  - cd ..
  - ls -l
  - sudo apt update
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade cython
  - pip3 install --upgrade buildozer
  - pip3 install --upgrade python-for-android
  - export PATH=$PATH:~/.local/bin/
  - ls -l
  - echo "TODO COMPILE 32bit"
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/mobileapp001-0.3-armeabi-v7a-debug.apk" --tag_name "v.0.3"
  - echo "TODO COMPILE 64bit"
  - ls -l /home/travis/
  - ls -l /home/travis/build/WISEPLAT/mobile_app_001/
  - ls -la
  - rm -r -f .buildozer
  - ls -la
  - rm -r -f /home/travis/build/WISEPLAT/mobile_app_001/.buildozer
  - ls -l /home/travis/
  - ls -l /home/travis/build/WISEPLAT/mobile_app_001/
  - ls -l
  - yes | cp -f buildozer-64bit.spec buildozer.spec
  - yes | buildozer android release
  - ls -la
  - ls bin/ -l
  - echo "TODO"
  - gem install dpl --pre
  - dpl releases --token $g_token --file "bin/mobileapp001-0.3-arm64-v8a-release-unsigned.apk" --tag_name "v.0.3"
  - echo "OK"
